# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Titto
tagline:          'Android developer'
description:      'Passionate android developer'
url:              http://tittojose.me/
baseurl:          /

author:
  name:           'Titto Jose K'
  url:            http://tittojose.me/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
      - jekyll-sitemap

google:
  verification: "nmaghktbQvkiu7hY7f2xr35N1mPhZVz1tljrd0cM0wA" # Google webmaster verification
