# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Titto
tagline:          'Android developer'
description:      'Passionate android developer'
url:              https://www.google.co.in/imgres?imgurl=http%3A%2F%2Fwww.manutd.com%2F~%2Fmedia%2F510AE241278B45FF97125DC1E1E32CBF.ashx&imgrefurl=http%3A%2F%2Fwww.manutd.com%2F&docid=9e5rvhE_Sd_HsM&tbnid=VYzWFRVQN_KgOM%3A&vet=1&w=696&h=699&bih=638&biw=1366&q=manchester%20united&ved=0ahUKEwi9tK3exbfSAhUT1GMKHTCyBm8QMwgwKAAwAA&iact=mrc&uact=8#h=699&imgrc=VYzWFRVQN_KgOM:&vet=1&w=696
baseurl:          /

author:
  name:           'Titto Jose K'
  url:            http://tittojose.me/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

gems:
      - jekyll-sitemap

google:
  verification: "nmaghktbQvkiu7hY7f2xr35N1mPhZVz1tljrd0cM0wA" # Google webmaster verification
